import { type NextPage } from 'next'
import Head from 'next/head'
import BooksSection from '~/components/BooksSection'
import StateWrapper from '~/components/StateWrapper'
import MainLayout from '~/layouts/MainLayout'
import { api } from '~/utils/api'

const Home: NextPage = () => {
    const bestSellersQuery = api.book.getBestSellers.useQuery({
        take: 15,
        lastDays: 7,
    })

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <StateWrapper
                    data={bestSellersQuery.data}
                    isLoading={bestSellersQuery.isLoading}
                    isError={bestSellersQuery.isError}
                    Empty={
                        <div>Currently there are no books in the store.</div>
                    }
                    Error={
                        <div>
                            Something went wrong and we could't get the best
                            sellers list.
                        </div>
                    }
                    NonEmpty={(books) => (
                        <BooksSection title={'Best sellers'} books={books} />
                    )}
                />
            </MainLayout>
        </>
    )
}

export default Home
