import { type NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '~/components/Sidebar'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex h-full md:flex-row flex-col">
                <Sidebar />
                <main></main>
            </div>
        </>
    )
}

export default Home
